#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# (c) ACE 

import os

class Config(object):
    # get a token from @BotFather
    pass
    """
    BOT_TOKEN = os.environ.get("BOT_TOKEN", "6103524529:AAGMbltmFHLulnBqSyi50CCZCLYeVrEFG8g")
    API_ID = int(os.environ["API_ID", 24250238]
    API_HASH = os.environ["API_HASH", "cb3f118ce5553dc140127647edcf3720"]
    AUTH_USERS = "6175650047"""
# jisko bhi is repo ko deploy karne me error aa raha ho ( https://t.me/Stubborn1223 ) ye mere TG ka id ha message karke iska screen shot send kar dena me error solve kar dunga. 
